### ISSUE TITLE
Virus in TrendMicro detection

### ISSUE THREAD

**Issue by gthelp** [unchase/Unchase.OpenAPI.Connectedservice#28]
I installed the extension and when I publish my code, TrendMicro is saying the backdoor trojans are embedded in exe file and a script runs to try to turn off my system restore. 

![image](https://user-images.githubusercontent.com/17496668/87668764-b3fdb280-c73a-11ea-854e-1d709c4f1bf5.png)
![image](https://user-images.githubusercontent.com/17496668/87668824-d42d7180-c73a-11ea-87cb-2b3f43ae6148.png)

**Comment by unchase** [comment]
Hi @gthelp
The detected malware cannot be found in the extended service.
The connected service is open source.
You are probably using some third-party libraries in your application that contain a virus.

Or is it a false positive.

**Comment by unchase** [comment]
Hi, @gthelp 

I received email by Microsoft about the blocking of the extension due to a complaint about the presence of a backdoor in it.

Please check the extension separately with your security tool, because my checks showed that the extension is clean.

You can see the result of checking the extension by virustotal.com with [this link](https://www.virustotal.com/gui/file/14c0d62065275fc4c04033e85f7f93a27277a9b47fb0e80d3cc5127a237f0126/detection)

![det1](https://user-images.githubusercontent.com/29679226/88725786-50f61d80-d135-11ea-8b87-0f0d6c284259.png)

![det2](https://user-images.githubusercontent.com/29679226/88725795-5489a480-d135-11ea-99dc-1054ab3f8e45.png)
