### ISSUE TITLE
Code Generation: Plans to configure usage of Newtonsoft or System.Text.Json?

### ISSUE THREAD

**Issue by StefanOssendorf** [unchase/Unchase.OpenAPI.Connectedservice#32]
Hi.

Are there any plans to modify the code generation to be able to switch between System.Text.Json or Newtonsoft as serializer?

Thanks in advance
Stefan

**Comment by unchase** [comment]
The Connected Service based on [NSwag](https://github.com/RicoSuter/NSwag):

> Support for System.Text.Json
NSwag cannot fully support System.Text.Json because the library does not expose metadata to generate schemas. However we internally try to map System.Text.Json options to a custom Newtonsoft.JSON contract resolver which should cover most scenarios.

> See this epic for more information: https://github.com/RicoSuter/NSwag/issues/2243

**Comment by StefanOssendorf** [comment]
Thanks for the pointer :-)

**Comment by StefanOssendorf** [comment]
Hi. I know this is closed but I didn't want to open a duplicate. If you prefer a new one just say so and I'll copy my question there ;-).

Is STJ now supported? As far as I understand the linked issue from above it's in there for the client generation.

**Comment by unchase** [comment]
Hi, @StefanOssendorf 

You can track the current status [here](https://github.com/RicoSuter/NSwag/issues/2243).
Once this is implemented on the library side, I'll add support to the extension.
