### ISSUE TITLE
Task configuration seems not to load

### ISSUE THREAD

**Issue by bjoholen** [unchase/Unchase.OpenAPI.Connectedservice#43]
I used this a first time with a configuration. Then i needed to run it again, but then I had to re-enter the configuration.

**Comment by unchase** [comment]
Hi, @bjoholen 
Can you clarify what kind of data in the configuration you had to re-enter?

**Comment by bjoholen** [comment]
Hi,
I guess i have missed something completely. I double click on «Connected Services» and can then click on Unchase and i get this
***@***.***D7172E.9CBBD950]

I would have imagened that i could right click on «ConnectedService.json» and then «run custom tool» or something like that.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by liamlaverty** [comment]
I thought I was having this issue, but seems to be user error on my part. Some people may find it handy to know the following, since this turns up near the top of search engines for "Unchase Swagger configuration empty on update"

To regenerate the client using the existing settings:

- Open Solution Explorer at the project 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/7046713/140501734-9b2b1ad4-0413-4a66-b25c-75839bcaddab.png">

- Right click the **folder** the service is in, **not** the _Connected Services_ option

<img width="558" alt="image" src="https://user-images.githubusercontent.com/7046713/140501989-c74087c1-97e3-48aa-aa92-77fb3d53f712.png">

- Click _Update Unchase OpenAPI (Swagger) Connected Service..._

- The configuration window should then open, with all of your previously entered settings pre-filled

**Comment by unchase** [comment]
Hi @liamlaverty
Thx for clarification of this for users.
